models.py
from Intel_work_demo import db


class Workload(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    run_uri = db.Column(db.String(40), nullable=False)
    workload = db.Column(db.String(100), nullable=False)
    testcase = db.Column(db.String(100), nullable=False)
    date = db.Column(db.DateTime)
    cloud = db.Column(db.String(10))
    microarchitecture = db.Column(db.String(100))
    unit = db.Column(db.String(10))
    value = db.Column(db.Integer)

__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_mysqldb import MySQL
from flask_sqlalchemy import SQLAlchemy
import yaml
from os import path

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    config_file = path.join(path.dirname(__file__), "config.yaml")
    with open(config_file, "r") as file:
        config = yaml.safe_load(file)

    app.config[
        "SQLALCHEMY_DATABASE_URI"
    ] = f"mysql://{config['mysql_user']}:{config['mysql_password']}@{config['mysql_host']}/{config['mysql_db']}"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)
    mysql = MySQL(app)

    migrate = Migrate(app, db)

    from .views import views

    app.register_blueprint(views, url_prefix="/")

    from .models import Workload

    # create Datebase Object
    with app.app_context():
        db.create_all()

    return app

views.py
from flask import Blueprint, render_template, request
from .benchmarking import (
    get_all_workload,
    get_workload_data,
    get_testcase_data,
    get_cloud_data,
    get_machine_type_data,
)

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home_page.html")


@views.route("/about")
def about():
    return render_template("about.html")


@views.route("/admin")
def admin():
    return render_template("admin.html")


@views.route("/benchmarking")
def benchmarking():
    workloads = get_workload_data()
    workload_ip = request.args.get("workload")
    testcase_ip = request.args.get("testcase")
    cloud_ip = request.args.get("cloud")
    testcases = []
    clouds = []
    microarchitectures = []
    if workloads:
        testcases = get_testcase_data(workload_ip)
        if testcases:
            clouds = get_cloud_data(workload_ip, testcase_ip)
            if clouds:
                microarchitectures = get_machine_type_data(
                    workload_ip, testcase_ip, cloud_ip
                )
    return render_template(
        "benchmarking.html",
        workloads=workloads,
        workload_ip=workload_ip,
        testcases=testcases,
        testcase_ip=testcase_ip,
        clouds=clouds,
        cloud_ip=cloud_ip,
        microarchitectures=microarchitectures,
    )


@views.route("/workloads")
def workload():
    return render_template("workload.html")

templates/about.html
{% extends "base_page.html" %}
<title>{% block title %} About {% endblock %}</title>
{% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/about.css') }}"
/>
<h2>Wellocme to about</h2>

<div class="about-section">
  <h1>About Us Page</h1>
  <p>Some text about who we are and what we do.</p>
  <p>
    Resize the browser window to see that this page is responsive by the way.
  </p>
</div>

<h2 style="text-align: center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="/w3images/team1.jpg" alt="Jane" style="width: 100%" />
      <div class="container">
        <h2>Jane Doe</h2>
        <p class="title">CEO & Founder</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>jane@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/w3images/team2.jpg" alt="Mike" style="width: 100%" />
      <div class="container">
        <h2>Mike Ross</h2>
        <p class="title">Art Director</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>mike@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/w3images/team3.jpg" alt="John" style="width: 100%" />
      <div class="container">
        <h2>John Doe</h2>
        <p class="title">Designer</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>john@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/admin.html
{% extends "base_page.html" %}
<title>{% block title %} Admin {% endblock %}</title>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/admin.css') }}"
/>
{% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/admin.css') }}"
/>

<div class="main-w3layouts wrapper">
  <h1>Admin only</h1>
  <div class="main-agileinfo">
    <div class="agileits-top">
      <form action="#" method="post">
        <input
          class="text"
          type="text"
          name="Username"
          placeholder="Username"
          required=""
        />
        <input
          class="text email"
          type="email"
          name="email"
          placeholder="Email"
          required=""
        />
        <input
          class="text"
          type="password"
          name="password"
          placeholder="Password"
          required=""
        />
        <input
          class="text w3lpass"
          type="password"
          name="password"
          placeholder="Confirm Password"
          required=""
        />
        <div class="wthree-text">
          <label class="anim">
            <input type="checkbox" class="checkbox" required="" />
            <span>I Agree To The Terms & Conditions</span>
          </label>
          <div class="clear"></div>
        </div>
        <input type="submit" value="SIGNUP" />
      </form>
      <p>Already have an Account? <a href="#"> Login Now!</a></p>
    </div>
  </div>
  <!-- copyright -->
  <div class="colorlibcopy-agile">
    <p>
      © 2018 Colorlib Signup Form. All rights reserved | Design by
      <a href="https://colorlib.com/" target="_blank">Colorlib</a>
    </p>
  </div>
  <!-- //copyright -->
  <ul class="colorlib-bubbles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div>
{% endblock %}

templates/base_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/base.css') }}"
    />
    <script src="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.6/dist/ag-grid-community.min.noStyle.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.6/styles/ag-grid.css"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.6/styles/ag-theme-alpine.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.about')}}">About</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('views.admin')}}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('views.benchmarking')}}"
                >BenchMarking</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('views.workload')}}"
                >All Workload</a
              >
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container">{% block content %} {% endblock %}</div>

    <footer>
      
      <div class="footer-bottom">
        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <div class="footer-site-info">
                <i class="fa fa-copyright" aria-hidden="true"></i>copyright©
                <a
                  href="https://www.youtube.com/watch?v=pdr4IzBpacI&t=34s"
                  target="_blank"
                  >Intel pvt ltd
                </a>
              </div>
            </div>

            <div class="col-md-6">
              <nav
                id="footer-navigation"
                class="site-navigation footer-navigation centered-box"
                role="navigation"
              >
                <ul
                  id="footer-menu"
                  class="nav-menu styled clearfix inline-inside"
                >
                  <li
                    id="menu-item-26"
                    class="menu-item menu-item-type-custom menu-item-object-custom menu-item-26"
                  >
                    <a href="#">Support</a>
                  </li>
                  <li
                  <i class="fa fa-phone" aria-hidden="true"></i> Phone:
                  <a href="">+91-9122588799</a>
                  </li>
                  <li
                  <i
                  class="fa fa-envelope"
                  style="color: red"
                ></i>
                email:
                <a>ashu00619@gmai.com</a>
                  </li>
                </ul>
              </nav>
            </div>

            <div class="col-md-3">
              <div id="footer-socials">
                <div class="socials inline-inside socials-colored">
                  <a
                    href="#"
                    target="_blank"
                    title="Facebook"
                    class="socials-item"
                  >
                  <i aria-hidden="true" class="fa-facebook"></i>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    title="Twitter"
                    class="socials-item"
                  >
                    <i class="fab fa-twitter twitter"></i>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    title="Instagram"
                    class="socials-item"
                  >
                    <i class="fab fa-instagram instagram"></i>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    title="YouTube"
                    class="socials-item"
                  >
                    <i
                      class="fa fa-youtube-play"
                      style="color: red"
                    ></i>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    title="Telegram"
                    class="socials-item"
                  >
                    <i class="fab fa-telegram telegram"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static',filename='js/base.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
  </body>
</html>

templates/benchmarking.html
{% extends "base_page.html" %}
<title>{% block title %} Benchmark {% endblock %}</title>

{% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/benchmarking.css') }}"
/>


<h2>Wellocme to benchmarking</h2>
<div class="card">
    <div class="card-header text-bg-primary mb-3">
      Filters
    </div>
    <div class="card-body">
        <div class="row">
            <div class = "col-md-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Date Filter</span>
                    <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                  </div>
            </div>      
            <div class = "col-md-2">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Workload</span>
                    <select class="form-control" id="workload-select" aria-label="Default select example" onchange="get_testcases()">
                      {% for workload in workloads %} 
                       <option>{{ workload }}</option>
                      {% endfor %}
                    </select>
                  </div>
            </div> 
            <div class = "col-md-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">TestCase</span>
                    <select class="form-control" id="testcase-select" aria-label="Default select example" onchange="get_cloud();get_highchart()">
                      {% for testcase in testcases %} 
                       <option>{{ testcase }}</option>
                      {% endfor %}
                    </select>
                  </div>
            </div> 
            <div class = "col-md-2">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Cloud</span>
                    <select class="form-control" id="cloud-select" aria-label="Default select example"  onchange="get_microarchitecture();get_highchart()">
                      <option selected>select cloud</option>
                      {% for cloud in clouds %} 
                       <option>{{ cloud }}</option>
                      {% endfor %}
                    </select>
                </div> 
            </div>
            <div class = "col-md-2">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Microarchitecture</span>
                    <select class="form-control" id="microarchitecture-select" aria-label="Default select example" onchange="get_highchart()">
                      {% for microarchitecture in microarchitectures %} 
                       <option>{{ microarchitecture }}</option>
                      {% endfor %}
                    </select>
                  </div>
            </div> 
        </div>
        
    </div>
  </div>

  <div class="card">
    <div class="card-header text-bg-primary mb-3">
      Highchart Visualization
    </div>
    <div class="card-body">
        <div id='highchart-body'>
            
        </div>
        
    </div>
  </div>

  <div class="card">
    <div class="card-header text-bg-primary mb-3">
      Ag-grid Visualization
    </div>
    <div class="card-body">
        <div id="myagGrid" class="ag-theme-alpine" style="height: 500px"></div>
            
        </div>
        
    </div>
  </div>
  <script src="{{ url_for('static',filename='js/benchmarking.js') }}"></script>
  {% endblock %}
</div>

templates/home_page.html
{% extends 'base_page.html' %} {% block title %}Home{% endblock %} {% block
content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/home.css') }}"
/>
<h1>Wellcome to Intel Home page</h1>
<img
  src="{{ url_for('static', filename='img/Intelimg1.png')}}"
  alt="Loading Image"
  width="60%"
  height="50%"
/>
<h3>First Image</h3>
<img
  src="{{ url_for('static', filename='img/Intelimg2.jpg')}}"
  alt="Loading Image"
  width="60%"
  height="40%"
/>
<h3>second Image</h3>
<img
  src="{{ url_for('static', filename='img/Intelimg3.jpg')}}"
  alt="Loading Image"
  width="60%"
  height="40%"
/>
<h3>second Image</h3>
{% endblock %}

templates/workload.html
{% extends "base_page.html" %}
<title>{% block title %} Workload {% endblock %}</title>

{% block content %}

<h2>Wellocme to workload</h2>
<div id="myGrid" class="ag-theme-alpine" style="height: 500px"></div>
<script src="{{ url_for('static', filename='js/workload.js') }}"></script>
<script type="text/javascript"></script>

{% endblock %}